# Generated by Django 2.2 on 2019-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreatQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('great_quote', models.CharField(max_length=2000)),
                ('narrator', models.CharField(max_length=200)),
            ],
        ),
    ]
